### ISSUE TITLE
impl Display rather than print()

### ISSUE THREAD

**Issue by BastienVigneron** [biscuit-auth/biscuit-rust#112]
Is there any particular reason for using a `biscuit.print()` rather than implementing the Display trait ?

**Comment by Geal** [comment]
there was no real reason, implementing `Display` would make sense, that should be an easy PR

**Comment by BastienVigneron** [comment]
See https://github.com/biscuit-auth/biscuit-rust/pull/117

**Comment by Geal** [comment]
closing this now than #117 is merged, thanks!
