### ISSUE TITLE
Lookup facts after authorization

### ISSUE THREAD

**Issue by flyboarder** [biscuit-auth/biscuit-rust#123]
What is the process in order to query the token for facts once the authorizer has authorized the token?

**Comment by Geal** [comment]
the [`Authorizer::query` method](https://docs.rs/biscuit-auth/latest/biscuit_auth/struct.Authorizer.html#method.query) should be used. Unfortunately, it was not usable from biscuit-wasm, but now that #124 is mrge, I can update that library and make it available

**Comment by Geal** [comment]
https://github.com/biscuit-auth/biscuit-wasm/pull/12 was merged, closing this
