### ISSUE TITLE
Parsing chained method calls

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit-rust#146]
The following doesn't parse

```
[1].intersection([1]).contains(1);
```

The following parses:

```
([1].intersection([1])).contains(1);
```

i have noticed the same issue in biscuit haskell, so i suspect it's related to how the parsers are written. i'm not sure yet how hard it would be to fix (to make chained methods left-associative instead of right-associative). In any case, the `Display` implementation on expressions correctly parenthesizes the expression (since it is not aware of precedence rules, it adds parens everywhere, to be sure).

So it's not something someone could copy from generated datalog code, but it's still something that could be expected to work.

**Comment by Geal** [comment]
that sounds interesting yes, I'll add that to the parser
