### ISSUE TITLE
Datalog boolean expression == does not evaluate properly

### ISSUE THREAD

**Issue by Tipnos** [biscuit-auth/biscuit-rust#147]
The following datalog code does not produce a bar("d") fact.

```
foo(true);

bar("d") <- foo($b),
$b == true;
```

For info this one does:
```
foo(true);

bar("d") <- foo($b),
$b;
```

**Comment by divarvel** [comment]
Indeed, equality is not implemented on booleans, so it falls in the default case, which is to return false every time.

I'll add it to samples to make sure other implementations follow suit

**Comment by Geal** [comment]
the spec indicates that booleans support equality and inequality:
> A boolean is true or false. It supports the following operations: ==, !=, ||, &&, set inclusion.

**Comment by divarvel** [comment]
> the spec indicates that booleans support equality and inequality:
> 
> > A boolean is true or false. It supports the following operations: ==, !=, ||, &&, set inclusion.

Ah my bad, i must have misread then
