### ISSUE TITLE
Integration with serde

### ISSUE THREAD

**Issue by meh** [biscuit-auth/biscuit-rust#17]
It would be baller if there was some fancy way to insert/extract facts using serde, at the moment it's kind of painful to manage facts.

**Comment by divarvel** [comment]
the library now supports parameter injection, at runtime and at compile time through proc macros.

Was there something specific about serde that would make its use relevant? The intended way to  _add_ facts to a token block (or authorizer) is through the use of the `_merge!` macros. The intended way to retrieve facts is through querying.
