### ISSUE TITLE
Expressions: prevent panics & overflows

### ISSUE THREAD

**Issue by daeMOn63** [biscuit-auth/biscuit-rust#29]
Math operations needs to be checked for invalid operations (such as Div by zero) or potential overflow / underflow. In such case, the expression must returns an error

**Comment by Geal** [comment]
fixed in https://github.com/CleverCloud/biscuit-rust/commit/700171012293be8da6c4243f5d9391ab6c078e49 (it returns an Option for now, maybe expression and rule evaluation could have more specific errors)
