### ISSUE TITLE
Expressions: group feature

### ISSUE THREAD

**Issue by daeMOn63** [biscuit-auth/biscuit-rust#31]
With the boolean operation, we'll soon need a grouping option like parenthesis for operation ordering.

for cases like:
```
$a > 12 and $b == 42 or $c != 0
($a > 12 and $b == 42) or $c != 0
$a > 12 and ($b == 42 or $c != 0)
```

**Comment by Geal** [comment]
fixed in https://github.com/CleverCloud/biscuit-rust/commit/2302f186a702e6046f16f560cf176af5a1b812a4
