### ISSUE TITLE
Biscuit CLI

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit-rust#34]
Since https://github.com/CleverCloud/biscuit-rust is the canonical implementation of biscuit, it would make sense for it to harbor a canonical CLI tool, allowing people to manage biscuits.

Here are a couple ideas based on my experience with macaroons at my current job.

I think the default format for biscuits should be base64, with a `--raw` flag for raw binary.

# Inspecting a biscuit

The goal here is to display contents in a human-readable manner (ideally with a syntax that could be used as-is with libs: for instance, facts, rules and checks separated with `;\n`.

An extra `--check-signature` option would allow to verify the signature, with a provided public key.

An issue with the equivalent feature for macaroons is that displaying caveats + signature is equivalent to displaying the macaroon itself. People are careful not sharing a token, as they correctly understand it's sensitive info, but i've seen people share caveats + signatures without realizing it was equivalent to sharing the token. So here, `inspect` should not display the whole signature (or anything allowing to reconstruct the biscuit) without an explicit flag.

```
biscuit inspect <<< $BISCUIT

biscuit inspect --check-signature $PUBLIC_KEY <<< $BISCUIT

```

# Verifying a biscuit

```
cat verifier <<EOF
allow if true;
EOF
biscuit verify --max-facts 50 --verifier ./verifier < ./biscuit
```

# Generating a biscuit

The rationale for reading the private key from an env var is to avoid having it in the command history or in a clear text file

```
BISCUIT_PRIVATE_KEY=$(get the private key from a secure storage) biscuit generate << EOF
operation(#authority, #read);
check if current_time(#ambient, $time), $time < 2021-05-15T20:18:52+02:00;
EOF
```

# Adding a block

This could be something close to `biscuit-generate` (without the private key). I'm not sure which of the biscuit or the block contents should read from stdin and which should be read from an argument or a file.

**Comment by divarvel** [comment]
It's a bit "pêle-mêle" but that can start a discussion.

**Comment by Geal** [comment]
I guess this was discussed :smile: 
https://github.com/biscuit-auth/biscuit-cli
