### ISSUE TITLE
Rule Parsing Error

### ISSUE THREAD

**Issue by UndisclosedDev** [biscuit-auth/biscuit-rust#41]
When testing the example code

```rust
  let mut v3 = biscuit2.verify(public_key)?;
  v3.add_resource("/a/file2.txt");
  v3.add_operation("read");
  v3.add_rule("allow if right(#authority, \"/a/file2.txt\", #read)");
  v1.deny();
```
I am getting this error
`rule parsing error: Error(Error { input: "if right(#authority, \"/a/file2.txt\", #read)", code: Char, message: None })`

What is wrong with the rule?
This code is part of the example for Rust

Where can I get more information about rule construction?

I would appreciate any help you can provide on this matter.

**Comment by Geal** [comment]
right, the readme is wrong here, and the docs should also make that more explicit (and the parse error too). You should use [add_policy](https://docs.rs/biscuit-auth/1.1.0/biscuit_auth/token/verifier/struct.Verifier.html#method.add_policy) for allow/deny policies

**Comment by Geal** [comment]
fixed the readme: 7ce1d31

**Comment by UndisclosedDev** [comment]
Thanks for your reply.

Is there any info available where I can learn about the difference between a policy and a rule, and how to use them correctly?

I have read the foundation, tutorial and specifications; but the information about rules is not clear to me.

Thank you

**Comment by Geal** [comment]
there's now some published docs here: https://www.biscuitsec.org/docs/getting-started/policies/
