### ISSUE TITLE
Return both policy and check errors in the error type

### ISSUE THREAD

**Issue by clementd-fretlink** [biscuit-auth/biscuit-rust#49]
Currently, all the check errors are collected, but policies are tried only if there is no check error.
This makes debugging auth errors a bit harder than necessary, and does not provide meaningful perf improvements (the authorizer datalog has to be evaluated before checking block checks anyway).

I think a fine default is to run all checks and the policy list as well. A perf improvement would be to early abort evaluation after each block.

**Comment by Geal** [comment]
good idea, done in d73f08b
