### ISSUE TITLE
Return the matched query + variable bindings in the success type

### ISSUE THREAD

**Issue by clementd-fretlink** [biscuit-auth/biscuit-rust#50]
It's an improvement i made in the haskell lib, which makes it convenient to extract data from the token for use by application code. This makes it easy to ensure that the token carries the needed info and avoid having failures happen after the auth check.

**Comment by Geal** [comment]
could you show an example of this use?

**Comment by divarvel** [comment]
Of course: https://www.biscuitsec.org/docs/Usage/haskell/#query-data-from-the-authorizer

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes       #-}

import Auth.Biscuit

checkBiscuit :: Biscuit -> IO Text
checkBiscuit b =
  result <- authorizeBiscuit b [authorizer| allow if user($user); |]
  case result of
    Left a  -> throwError …
    Right success ->
      case getSingleVariableValue (getBindings success) "user" of
        Just userId -> pure userId
        -- ^ this will only match if a unique user id is
        -- retrieved from the matched variables
        Nothing -> throwError …
```

the general idea is that the success value returned when the biscuit was authorized carries the bindings that matched the allow query. With a couple helpers, it makes it easy to get regular values. In the example, i've used helpers that only succeed if there is a unique binding for a given variable, but lower-level access is possible.

**Comment by Geal** [comment]
I see, that would be useful. The rust library behaves differently though, it stops at the first match instead of trying them all

**Comment by divarvel** [comment]
Do you mean "the first policy that matches", or "the first binding map within a policy"? (Since policies can contain several "or" clauses)

**Comment by Geal** [comment]
The firet binding within a policy. If there are multiple variable combinations that a policy could match, it will stop at the first one. The goal is to find at least one match for authorization, while queries are there if we want all the possible matches
