### ISSUE TITLE
Security Vulnerability: Replace chrono with time 0.3

### ISSUE THREAD

**Issue by PotatoTech** [biscuit-auth/biscuit-rust#54]
chrono has a security vulnerability ([RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159)). It is also unmaintained, as the last release was in September 2020. To resolve this issue, chrono should be replaced with the time crate.

**Comment by Geal** [comment]
this shoulld be fixed by https://github.com/biscuit-auth/biscuit-rust/commit/6da6509549dea8b4e0cdb66cb7e77492c2e77d5e

I'll do a bit more testing then a release

**Comment by Geal** [comment]
since biscuit only uses chrono to parse and serialize in RFC3339 format, it is not affected by the localtime_r vulnerability
