### ISSUE TITLE
Are Symbols a thing is v2?

### ISSUE THREAD

**Issue by Eh2406** [biscuit-auth/biscuit-rust#56]
The docs say that they are https://docs.rs/biscuit-auth/latest/biscuit_auth/#symbols-and-symbol-tables
But the blog post claims that they are not https://www.biscuitsec.org/blog/biscuit-2-0/#removing-the-symbol-type
Probably a docs bug.

**Comment by Geal** [comment]
symbols were removed, but the symbol table is still used, to store fact names and strings. I updated the docs in https://github.com/biscuit-auth/biscuit-rust/commit/12b1b413fad2a6f1677295742ca1aa58796289d7, thanks for the report
