### ISSUE TITLE
Compile-time parsing of datalog blocks

### ISSUE THREAD

**Issue by divarvel** [biscuit-auth/biscuit-rust#67]
This builds upon #66 

Once we have a compelling solution for parameter substitution, the next step is to move parsing to compile-time, through a proc macro.

Here's how is could look like:

```rust
let b = block!(r"check if time($time), $time < {0};", now);
let a = authorizer(r"allow if {cond};", cond = true);
```

So something really close to `println!()`, but
- without support for implicit parameter naming (either they are numbered, or they are named);
- without support for formatting modifiers (here we're building an AST, so we can use values as is

I'm not sure about support for directly referring expressions withing curly braces, as is possible in println on rust 1.58+ (it might be hard to support).

It would work with standard rust values through `TryInto<Term>`.

For reference, biscuit-haskell does something quite similar (with direct slicing of variables in the datalog string instead of named parameters), and that provides both good DX (it removes the need for error checks at runtime) and perf (parsing is paid only once, at compile time).

**Comment by divarvel** [comment]
So it's now part of a dedicated crate.
What's missing is full support of third party tokens, and I think it'd be best to have it part of the default crate (maybe feature gated), so that would require shuffling things a bit in the workspace

**Comment by Geal** [comment]
I guess we can close this now?

**Comment by divarvel** [comment]
yeah
